# Step 1 -  Load and EDA
- here we load the data and perfrom EDA
- for checking the null values and dtypes

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data.csv')
df.head()

,invoice_id,customer_id,transaction_date,product_id,quantity,unit_price,total,discount_rate,refund_flag,payment_method,country
0,INV0079407,C02045,2023-01-01,P048,2,8584,17168,0.14,0,Card,Germany
1,INV0581190,C14584,2023-01-01,P090,4,7779,31118,0.16,0,Card,UK
2,INV0410888,C10301,2023-01-01,P043,5,6183,30913,0.32,0,Card,US
3,INV0429115,C10733,2023-01-01,P085,5,14,68,0.39,0,Card,India
4,INV0020948,C00558,2023-01-01,P006,5,15309,76547,0.24,0,UPI,US

In [11]:
df.info()    # We can check Dtype and Null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 793351 entries, 0 to 793350
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   invoice_id        793351 non-null  object
 1   customer_id       793351 non-null  object
 2   transaction_date  793351 non-null  object
 3   product_id        793351 non-null  object
 4   quantity          793351 non-null  int64
 5   unit_price        793351 non-null  int64
 6   total             793351 non-null  int64
 7   discount_rate     793351 non-null  float64
 8   refund_flag       793351 non-null  int64
 9   payment_method    793351 non-null  object
 10  country           793351 non-null  object
dtypes: float64(1), int64(4), object(6)
memory usage: 66.6+ MB

In [12]:
df.isnull().sum()      # To chechk null values

invoice_id          0
customer_id         0
transaction_date    0
product_id          0
quantity            0
unit_price          0
total               0
discount_rate       0
refund_flag         0
payment_method      0
country             0
dtype: int64

In [13]:
df.nunique()      # Helps to understand how many customer's  data here and same for another columns

invoice_id          793351
customer_id          19970
transaction_date       720
product_id             100
quantity                 5
unit_price           20759
total                70391
discount_rate           41
refund_flag              2
payment_method           5
country                 10
dtype: int64

In [14]:
df.describe()   # For STD, count, mean.....

,quantity,unit_price,total,discount_rate,refund_flag
count,793351.000000,793351.000000,793351.000000,793351.000000,793351.000000
mean,3.001179,6321.968230,18964.420942,0.200107,0.055127
std,1.414622,5367.747432,19925.866928,0.115571,0.228228
min,1.000000,5.000000,5.000000,0.000000,0.000000
25%,2.000000,1879.000000,4053.000000,0.100000,0.000000
50%,3.000000,5162.000000,12487.000000,0.200000,0.000000
75%,4.000000,9683.000000,27613.000000,0.300000,0.000000
max,5.000000,21000.000000,105000.000000,0.400000,1.000000

In [15]:
# We can see that here date is in string so we have to convert it

df['transaction_date'] = pd.to_datetime(df['transaction_date'])